import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./ui/globals.css";
import NavigationBar from "./ui/navigationBar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="text-xs md:text-base xl:text-lg">
      <body className={inter.className}>
        <div className="grid grid-rows-[auto_1fr]">
          <NavigationBar height="h-12" spacing="px-4"/>
          {children}
        </div>
      </body>
      
    </html>
  );
}
